/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CardGame.Campo;

import CardGame.Cartas.Carta;
import CardGame.Usuario.Jogador;
import javax.swing.DefaultListModel;

/**
 *
 * @author Paulo Victor
 */
public class CampoDeBatalhaDialog extends CampoDeBatalha {

    /**
     * Creates new form CampoDeBatalhaDialog
     */
    public CampoDeBatalhaDialog(Jogador jogadorAzul, Jogador jogadorVermelho) {
        super(jogadorAzul, jogadorVermelho);
        initComponents();
        this.setLocationRelativeTo(null);
        adjustLabels();
    }

    private void adjustLabels() {
        this.nomeDeckAzul.setText(jogadorAzul.getBaralho().getNome());
        this.nomeDeckVermelho.setText(jogadorVermelho.getBaralho().getNome());
        this.numCartasDeckAzul.setText(Integer.toString(jogadorAzul.getBaralho().getCartas().size()));
        this.numCartasDeckVermelho.setText(Integer.toString(jogadorVermelho.getBaralho().getCartas().size()));
    }

    private void atualizarCartasMao(Lado lado) {
        if (lado == Lado.AZUL) {
            DefaultListModel model = new DefaultListModel();

            for (Carta carta : jogadorAzul.getCartasNaMao().getCartas()) {
                model.addElement(carta);
            }

            listaCartasMaoAzul.setModel(model);
        } else {
            DefaultListModel model = new DefaultListModel();

            
            for (Carta carta : jogadorVermelho.getCartasNaMao().getCartas()) {
                model.addElement(carta);
            }

            listaCartasMaoVermelho.setModel(model);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelVermelho = new javax.swing.JPanel();
        campoVermelho = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        listaCartasMaoVermelho = new javax.swing.JList();
        invocarVermelho = new javax.swing.JButton();
        jogarForaVermelho = new javax.swing.JButton();
        fimTurnoVermelho = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        numCartasDeckVermelho = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        nomeDeckVermelho = new javax.swing.JLabel();
        panelAzul = new javax.swing.JPanel();
        campoAzul = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaCartasMaoAzul = new javax.swing.JList();
        invocarAzul = new javax.swing.JButton();
        jogarForaAzul = new javax.swing.JButton();
        fimTurnoAzul = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        nomeDeckAzul = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        numCartasDeckAzul = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        panelVermelho.setBackground(new java.awt.Color(255, 102, 102));
        panelVermelho.setPreferredSize(new java.awt.Dimension(0, 300));

        javax.swing.GroupLayout campoVermelhoLayout = new javax.swing.GroupLayout(campoVermelho);
        campoVermelho.setLayout(campoVermelhoLayout);
        campoVermelhoLayout.setHorizontalGroup(
            campoVermelhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        campoVermelhoLayout.setVerticalGroup(
            campoVermelhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 153, Short.MAX_VALUE)
        );

        jScrollPane2.setViewportView(listaCartasMaoVermelho);

        invocarVermelho.setText("Invocar");

        jogarForaVermelho.setText("Jogar Fora");

        fimTurnoVermelho.setText("Finalizar Turno");

        jLabel1.setText("Informações do Deck:");

        jLabel2.setText("Cartas Restantes:");

        numCartasDeckVermelho.setText("50");

        jLabel5.setText("Nome:");

        nomeDeckVermelho.setText("NomeDeck1");

        javax.swing.GroupLayout panelVermelhoLayout = new javax.swing.GroupLayout(panelVermelho);
        panelVermelho.setLayout(panelVermelhoLayout);
        panelVermelhoLayout.setHorizontalGroup(
            panelVermelhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelVermelhoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelVermelhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(campoVermelho, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelVermelhoLayout.createSequentialGroup()
                        .addGroup(panelVermelhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelVermelhoLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(invocarVermelho))
                            .addGroup(panelVermelhoLayout.createSequentialGroup()
                                .addGroup(panelVermelhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addGroup(panelVermelhoLayout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(nomeDeckVermelho))
                                    .addGroup(panelVermelhoLayout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(numCartasDeckVermelho)))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(panelVermelhoLayout.createSequentialGroup()
                                .addComponent(fimTurnoVermelho)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jogarForaVermelho)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        panelVermelhoLayout.setVerticalGroup(
            panelVermelhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelVermelhoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelVermelhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelVermelhoLayout.createSequentialGroup()
                        .addGroup(panelVermelhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jogarForaVermelho)
                            .addComponent(fimTurnoVermelho))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelVermelhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(nomeDeckVermelho))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelVermelhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(numCartasDeckVermelho))
                        .addGap(13, 13, 13)
                        .addComponent(invocarVermelho)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campoVermelho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        panelAzul.setBackground(new java.awt.Color(51, 51, 255));

        javax.swing.GroupLayout campoAzulLayout = new javax.swing.GroupLayout(campoAzul);
        campoAzul.setLayout(campoAzulLayout);
        campoAzulLayout.setHorizontalGroup(
            campoAzulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 580, Short.MAX_VALUE)
        );
        campoAzulLayout.setVerticalGroup(
            campoAzulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 153, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(listaCartasMaoAzul);

        invocarAzul.setText("Invocar");

        jogarForaAzul.setText("Jogar Fora");

        fimTurnoAzul.setText("Finalizar Turno");

        jLabel3.setText("Informações do Deck:");

        jLabel7.setText("Nome:");

        nomeDeckAzul.setText("NomeDeck2");

        jLabel4.setText("Cartas Restantes:");

        numCartasDeckAzul.setText("50");

        javax.swing.GroupLayout panelAzulLayout = new javax.swing.GroupLayout(panelAzul);
        panelAzul.setLayout(panelAzulLayout);
        panelAzulLayout.setHorizontalGroup(
            panelAzulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAzulLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelAzulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(campoAzul, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelAzulLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelAzulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelAzulLayout.createSequentialGroup()
                                .addComponent(jogarForaAzul)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(fimTurnoAzul))
                            .addGroup(panelAzulLayout.createSequentialGroup()
                                .addComponent(invocarAzul)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(panelAzulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addGroup(panelAzulLayout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(nomeDeckAzul)))
                                .addGap(1, 1, 1))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAzulLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(numCartasDeckAzul)))))
                .addContainerGap())
        );
        panelAzulLayout.setVerticalGroup(
            panelAzulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAzulLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(campoAzul, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelAzulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelAzulLayout.createSequentialGroup()
                        .addGroup(panelAzulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(invocarAzul)
                            .addGroup(panelAzulLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(panelAzulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7)
                                    .addComponent(nomeDeckAzul))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelAzulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(numCartasDeckAzul))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(panelAzulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jogarForaAzul)
                            .addComponent(fimTurnoAzul))))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelVermelho, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
            .addComponent(panelAzul, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelVermelho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelAzul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel campoAzul;
    private javax.swing.JPanel campoVermelho;
    private javax.swing.JButton fimTurnoAzul;
    private javax.swing.JButton fimTurnoVermelho;
    private javax.swing.JButton invocarAzul;
    private javax.swing.JButton invocarVermelho;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton jogarForaAzul;
    private javax.swing.JButton jogarForaVermelho;
    private javax.swing.JList listaCartasMaoAzul;
    private javax.swing.JList listaCartasMaoVermelho;
    private javax.swing.JLabel nomeDeckAzul;
    private javax.swing.JLabel nomeDeckVermelho;
    private javax.swing.JLabel numCartasDeckAzul;
    private javax.swing.JLabel numCartasDeckVermelho;
    private javax.swing.JPanel panelAzul;
    private javax.swing.JPanel panelVermelho;
    // End of variables declaration//GEN-END:variables
}
